// PRODUCTOS
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const POST_PRODUCT = 'POST_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'

//detalles
export const GET_DETAIL = "GET_DETAIL"
export const RESET_DETAIL = "RESET_DETAIL"

//searchbar
export const GET_NAME_PRODUCTS = 'GET_NAME_PRODUCTS'

//Categorias
export const GET_CATEGORIA = 'GET_CATEGORIA'
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export const EDIT_CATEGORIA = 'EDIT_CATEGORIA'
export const ORD_BYNAME = 'ORD_BYNAME'
export const ORD_BYPRICE = 'ORD_BYPRICE'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

// CARRITO
export const ADD_ITEM = 'ADD_ITEM'
export const REST_ITEM = "REST_ITEM"
export const DELETE_ITEM = 'DELETE_ITEM'
export const GET_CARRITO = "GET_CARRITO"

// export const SUM_CART = "SUM_CART"
export const UPDATE_CART = "UPDATE_CART"
export const DELETE_CART = 'DELETE_CART'
export const GET_CART = "GET_CART"
export const DELETE_CART_DB = "DELETE_CART_DB"

// AUTENTICACION Y USUARIO
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGOUT = "LOGOUT";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const RECOVERY_PASSWORD = "RECOVERY_PASSWORD"
export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_BY_EMAIL = "GET_BY_EMAIL"
export const GET_USER_D ="GET_USER_D"

//Usuario

export const POST_USER = 'POST_USER'
export const DELETE_USER = 'DELETE_USER'
export const CHANGE_CATEGORY ='CHANGE_CATEGORY'

// PEDIDOS
export const GET_PEDIDOS = "GET_PEDIDOS" //all
export const GET_PEDIDO_BY_USER = "GET_PEDIDO_BY_USER"
export const GET_PEDIDO_DETAIL = "GET_PEDIDO_DETAIL"
export const EDIT_STATUS_PEDIDO = "EDIT_STATUS_PEDIDO"
export const GET_PEDIDOS_STATUS = "GET_PEDIDOS_STATUS"
export const CREATE_PRODUCT = "CREATE_PRODUCT"

//PAGO
export const GET_BASKET_LOCAL_STORAGE = "GET_BASKET_LOCAL_STORAGE"
export const GET_MERCADOPAGO = "GET_MERCADOPAGO"
export const GET_PREF_ID = "GET_PREF_ID";